### ISSUE TITLE
README.md ... Spin is not interpreted.

### ISSUE THREAD

**Issue by drawkula** [Entomy/Spin-vscode#1]
> This extension provides support for Spin, an intepreted language for programmer the Parallax Propeller.

Spin gets compiled (typically on a PC) to bytecode which in turn gets interpreted on the Propeller.

**Comment by Entomy** [comment]
This behavior is often regarded as interpretation still, as "ready to use" binary code is not produced. I'll edit the description, but to just say it's a language for the Parallax Propeller with no classification.

**Comment by drawkula** [comment]
Things are weird today. With today's microcode based CPUs, the opcodes we get in touch with are a kind of interpreted too.
DotNet, Java and many other environments with languages being compiled for a simulated CPU or a whole VM are compiled and interpreted in a similar way.

Skipping this whole discussion by dropping the classification probably is the easies way not to discuss it for hours... :-)

**Comment by Entomy** [comment]
That's my exact reasoning. Compilation versus interpretation versus JIT etcetera is really a spectrum nowadays, and is more indicative of the toolchain than the language. I shouldn't have classified it to begin with.
